---
name: build

on:
  push:
    branches:
      - docs/**
      - backport/docs/**

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - run: echo "All build and integration workflows have succeeded!"
